name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.0.4
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Check flutter version
        run: flutter --version

      - name: Setup project
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build Android app
        run: flutter build apk

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Check flutter version
        run: flutter --version

      - name: Setup project
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
           name: android-app
           path: "./build/app/outputs/flutter-apk/app-release.apk"
