name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.0.4
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Check flutter version
        run: flutter --version

      - name: Run tests
        run: flutter test

      - name: Setup project
        run: flutter pub get

      - name: Build Android app
        run: flutter build apk

      - name: Build iOS app
        run: flutter build ios --release --no-codedesign
