name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.0.4
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Setup project
        run: flutter pub get

      - name: Run tests
        run: flutter test
        
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.0.4
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Build Android app
        run: flutter build apk

      - name: Upload Android artifacts
        uses: actions/upload-artifact@v2
        with:
           name: android-app
           path: "./build/app/outputs/flutter-apk/app-release.apk"

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2.0.4
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
        
      - name: Install required Ubuntu packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          
      - name: Configure flutter for Linux desktop
        run: flutter config --enable-linux-desktop
           
      - name: Build Linux application
        run: flutter build linux
        
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v2
        with:
           name: linux-app
           path: "./build/linux/x64/release/bundle/"

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Upload iOS artifacts
        uses: actions/upload-artifact@v2
        with:
           name: ios-app
           path: "./build/ios/iphoneos/Runner.app"
